# **Intellectual Property and Dissemination**  
## Intellectual Property

All information on intellectual property rights and ownership of results are specified in the [iRISE Grant Agreement](https://charitede.sharepoint.com/:f:/r/sites/iRISE/Shared Documents/General/Grant Agreement/AMD-101094853-4_Nov2023?csf=1&web=1&e=cuFpdE) under Article 16.  

## Dissemination Strategies  

The iRISE [Dissemination, Exploitation, and Communication Plan](https://charitede.sharepoint.com/:w:/r/sites/iRISE/Shared Documents/WP6/iRISE Dissemination Plan_Draft 1.2.docx?d=w7a63d0ea4a374c1bbe3b7fd98d0c7d2f&csf=1&web=1&e=jY54DT) outlines our preliminary strategies for effectively disseminating all expected iRISE project outcomes and maximising their impact. Additionally, we define our target audiences and how the messages will reach them. We will also describe how we will monitor engagement with iRISE outputs and the effectiveness of our dissemination, exploitation and communication activities.

As part of the strategies for disseminating iRISE project results, publications, and public engagement activities, we have developed guidelines and principles for the publication of research outcomes generated within iRISE. The latest version of our publication policy can be found here: [Publication policy](https://charitede.sharepoint.com/:w:/r/sites/iRISE/Shared%20Documents/WP7/Project%20Management/Coord.%20documents/Publication%20policy%20%26%20agreement/iRISE_Publication_Policy_2025-09-29_final.docx?d=w85f8ae135b8c47868bd417175702ba1f&csf=1&web=1&e=cQbAdf).  

The publication policy aims to ensure transparency, fairness, and proper acknowledgment of contributions while upholding the highest standards of research integrity and publication ethics. In addition, the Dissemination and Commination Plan and DMP will provide further details on the dissemination strategies and detailed activities.  
